services:
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: contact
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/